require approval

diff --git a/.github/workflows/cdk.yml b/.github/workflows/cdk.yml
--- a/.github/workflows/cdk.yml
+++ b/.github/workflows/cdk.yml
@@ -43,8 +43,7 @@ jobs:
 
     - name: Bootstrap CDK Environment
       run: |
-          cdk bootstrap aws://${{ env.aws_account }}/${{ env.aws_region }} || { echo "cdk bootstrap failed"; exit 1; }
-      
+          cdk bootstrap aws://${{ env.aws_account }}/${{ env.aws_region }} || { echo "cdk bootstrap failed"; exit 1; }      
   
     - name: Synth Stack
       run: |
@@ -54,4 +53,4 @@ jobs:
     - name: Deploy Stack
       run: |
         cd infra
-        cdk deploy --app "python infra.py" || { echo "cdk deploy failed"; exit 1; }
+        cdk deploy --app "python infra.py" --require-approval never || { echo "cdk deploy failed"; exit 1; }
