bootstrap

diff --git a/.github/workflows/cdk.yml b/.github/workflows/cdk.yml
--- a/.github/workflows/cdk.yml
+++ b/.github/workflows/cdk.yml
@@ -43,7 +43,8 @@ jobs:
 
     - name: Bootstrap CDK Environment
       run: |
-        cdk bootstrap --context aws_account=${{ env.aws_account }} --context aws_region=${{ env.aws_region }} || { echo "cdk bootstrap failed"; exit 1; }
+          cdk bootstrap aws://${{ env.aws_account }}/${{ env.aws_region }} || { echo "cdk bootstrap failed"; exit 1; }
+      
   
     - name: Synth Stack
       run: |
